version: '2'
services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 8000:8000
        restart: always
 
    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always
 
    node:
        depends_on:
            - reverseproxy
        image: tutorijal6-2:latest
        ports:
            - 3000:3000
        restart: always
    
    bulletin:
        depends_on:
            - reverseproxy
        image: bulletin:latest
        ports:
            - 4000:4000
        restart: always